import { Project, ProjectStats, ProjectFile, Milestone } from "./types";

export const mockFiles: ProjectFile[] = [
  {
    id: "f1",
    projectId: "1",
    fileName: "项目需求文档.pdf",
    fileSize: 1024000,
    fileType: "application/pdf",
    uploadedAt: new Date("2024-01-16"),
    url: "/uploads/requirement.pdf",
  },
  {
    id: "f2",
    projectId: "1",
    fileName: "设计稿.fig",
    fileSize: 2048000,
    fileType: "application/figma",
    uploadedAt: new Date("2024-01-18"),
    url: "/uploads/design.fig",
  },
  {
    id: "f3",
    projectId: "3",
    fileName: "性能测试报告.xlsx",
    fileSize: 512000,
    fileType: "application/vnd.ms-excel",
    uploadedAt: new Date("2024-01-24"),
    url: "/uploads/performance.xlsx",
  },
  {
    id: "f4",
    projectId: "5",
    fileName: "合同模板.docx",
    fileSize: 256000,
    fileType:
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    uploadedAt: new Date("2024-02-10"),
    url: "/uploads/contract-template.docx",
  },
  {
    id: "f5",
    projectId: "7",
    fileName: "财务报表.xlsx",
    fileSize: 768000,
    fileType: "application/vnd.ms-excel",
    uploadedAt: new Date("2024-03-05"),
    url: "/uploads/financial-report.xlsx",
  },
  {
    id: "f6",
    projectId: "9",
    fileName: "资产清单.xlsx",
    fileSize: 890000,
    fileType: "application/vnd.ms-excel",
    uploadedAt: new Date("2024-02-20"),
    url: "/uploads/asset-list.xlsx",
  },
  {
    id: "f7",
    projectId: "12",
    fileName: "会议纪要.pdf",
    fileSize: 340000,
    fileType: "application/pdf",
    uploadedAt: new Date("2024-03-12"),
    url: "/uploads/meeting-minutes.pdf",
  },
  {
    id: "f8",
    projectId: "15",
    fileName: "采购清单.xlsx",
    fileSize: 450000,
    fileType: "application/vnd.ms-excel",
    uploadedAt: new Date("2024-04-08"),
    url: "/uploads/procurement-list.xlsx",
  },
  {
    id: "f9",
    projectId: "18",
    fileName: "保险条款.pdf",
    fileSize: 1200000,
    fileType: "application/pdf",
    uploadedAt: new Date("2024-05-15"),
    url: "/uploads/insurance-terms.pdf",
  },
  {
    id: "f10",
    projectId: "20",
    fileName: "法律意见书.pdf",
    fileSize: 980000,
    fileType: "application/pdf",
    uploadedAt: new Date("2024-03-28"),
    url: "/uploads/legal-opinion.pdf",
  },
  {
    id: "f11",
    projectId: "22",
    fileName: "诉讼材料.pdf",
    fileSize: 1500000,
    fileType: "application/pdf",
    uploadedAt: new Date("2024-04-22"),
    url: "/uploads/litigation-docs.pdf",
  },
  {
    id: "f12",
    projectId: "25",
    fileName: "培训资料.pptx",
    fileSize: 2100000,
    fileType:
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    uploadedAt: new Date("2024-06-10"),
    url: "/uploads/training-materials.pptx",
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: "m1",
    projectId: "1",
    title: "需求分析",
    description: "完成需求调研和分析文档",
    status: "已完成",
    dueDate: new Date("2024-01-20"),
    completedDate: new Date("2024-01-19"),
    order: 1,
  },
  {
    id: "m2",
    projectId: "1",
    title: "UI设计",
    description: "完成界面设计和交互原型",
    status: "已完成",
    dueDate: new Date("2024-02-01"),
    completedDate: new Date("2024-01-31"),
    order: 2,
  },
  {
    id: "m3",
    projectId: "1",
    title: "前端开发",
    description: "完成前端页面开发",
    status: "进行中",
    dueDate: new Date("2024-02-15"),
    order: 3,
  },
  {
    id: "m4",
    projectId: "1",
    title: "后端开发",
    description: "完成API接口开发",
    status: "进行中",
    dueDate: new Date("2024-02-20"),
    order: 4,
  },
  {
    id: "m5",
    projectId: "1",
    title: "测试上线",
    description: "完成测试并部署上线",
    status: "未开始",
    dueDate: new Date("2024-03-01"),
    order: 5,
  },
  {
    id: "m6",
    projectId: "3",
    title: "性能分析",
    description: "分析当前系统性能瓶颈",
    status: "已完成",
    dueDate: new Date("2024-01-12"),
    completedDate: new Date("2024-01-11"),
    order: 1,
  },
  {
    id: "m7",
    projectId: "3",
    title: "优化实施",
    description: "执行优化方案",
    status: "已完成",
    dueDate: new Date("2024-01-20"),
    completedDate: new Date("2024-01-19"),
    order: 2,
  },
  {
    id: "m8",
    projectId: "3",
    title: "性能验证",
    description: "验证优化效果",
    status: "已完成",
    dueDate: new Date("2024-01-25"),
    completedDate: new Date("2024-01-24"),
    order: 3,
  },
  {
    id: "m9",
    projectId: "7",
    title: "监控需求分析",
    description: "分析监控系统功能需求",
    status: "已完成",
    dueDate: new Date("2024-01-15"),
    completedDate: new Date("2024-01-14"),
    order: 1,
  },
  {
    id: "m10",
    projectId: "7",
    title: "系统架构设计",
    description: "设计监控系统架构",
    status: "已完成",
    dueDate: new Date("2024-01-25"),
    completedDate: new Date("2024-01-24"),
    order: 2,
  },
  {
    id: "m11",
    projectId: "7",
    title: "核心功能开发",
    description: "开发监控核心功能",
    status: "进行中",
    dueDate: new Date("2024-02-10"),
    order: 3,
  },
  {
    id: "m12",
    projectId: "10",
    title: "资产盘点",
    description: "完成固定资产盘点",
    status: "已完成",
    dueDate: new Date("2024-02-05"),
    completedDate: new Date("2024-02-03"),
    order: 1,
  },
  {
    id: "m13",
    projectId: "10",
    title: "数据录入",
    description: "录入资产管理系统",
    status: "进行中",
    dueDate: new Date("2024-02-20"),
    order: 2,
  },
  {
    id: "m14",
    projectId: "13",
    title: "会议通知",
    description: "发送股东会议通知",
    status: "已完成",
    dueDate: new Date("2024-03-01"),
    completedDate: new Date("2024-02-28"),
    order: 1,
  },
  {
    id: "m15",
    projectId: "13",
    title: "议案准备",
    description: "准备会议议案材料",
    status: "进行中",
    dueDate: new Date("2024-03-10"),
    order: 2,
  },
  {
    id: "m16",
    projectId: "16",
    title: "供应商评估",
    description: "评估潜在供应商",
    status: "已完成",
    dueDate: new Date("2024-04-05"),
    completedDate: new Date("2024-04-03"),
    order: 1,
  },
  {
    id: "m17",
    projectId: "16",
    title: "合同谈判",
    description: "与供应商进行合同谈判",
    status: "进行中",
    dueDate: new Date("2024-04-20"),
    order: 2,
  },
  {
    id: "m18",
    projectId: "20",
    title: "案件材料整理",
    description: "整理合同纠纷相关材料",
    status: "已完成",
    dueDate: new Date("2024-03-15"),
    completedDate: new Date("2024-03-14"),
    order: 1,
  },
  {
    id: "m19",
    projectId: "20",
    title: "法律意见书撰写",
    description: "撰写法律意见书",
    status: "已完成",
    dueDate: new Date("2024-03-25"),
    completedDate: new Date("2024-03-23"),
    order: 2,
  },
  {
    id: "m20",
    projectId: "20",
    title: "诉讼准备",
    description: "准备诉讼材料",
    status: "进行中",
    dueDate: new Date("2024-04-10"),
    order: 3,
  },
];

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "网站重构项目",
    description: "对公司官网进行全面重构，采用最新技术栈",
    status: "进行中",
    priority: "高",
    category: "经营管理",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    dueDate: new Date("2024-03-01"),
    files: mockFiles.filter((f) => f.projectId === "1"),
    milestones: mockMilestones.filter((m) => m.projectId === "1"),
  },
  {
    id: "2",
    name: "移动应用开发",
    description: "开发iOS和Android移动应用",
    status: "待处理",
    priority: "中",
    category: "其他",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
    dueDate: new Date("2024-04-15"),
    files: [],
    milestones: [],
  },
  {
    id: "3",
    name: "数据库优化",
    description: "优化数据库查询性能，减少响应时间",
    status: "已完成",
    priority: "高",
    category: "资产管理",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-25"),
    dueDate: new Date("2024-01-25"),
    files: mockFiles.filter((f) => f.projectId === "3"),
    milestones: mockMilestones.filter((m) => m.projectId === "3"),
  },
  {
    id: "4",
    name: "API文档编写",
    description: "编写完整的API接口文档",
    status: "进行中",
    priority: "中",
    category: "其他",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-22"),
    dueDate: new Date("2024-02-10"),
    files: [],
    milestones: [],
  },
  {
    id: "5",
    name: "年度经营计划制定",
    description: "制定2024年度公司经营计划",
    status: "已完成",
    priority: "高",
    category: "经营管理",
    createdAt: new Date("2023-11-20"),
    updatedAt: new Date("2023-12-15"),
    dueDate: new Date("2023-12-31"),
    files: mockFiles.filter((f) => f.projectId === "5"),
    milestones: [],
  },
  {
    id: "6",
    name: "安全审计",
    description: "进行全面的安全漏洞审计",
    status: "已完成",
    priority: "高",
    category: "法务管理",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-15"),
    dueDate: new Date("2024-01-15"),
    files: [],
    milestones: [],
  },
  {
    id: "7",
    name: "性能监控系统",
    description: "搭建应用性能监控和告警系统",
    status: "进行中",
    priority: "高",
    category: "资产管理",
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-23"),
    dueDate: new Date("2024-02-28"),
    files: mockFiles.filter((f) => f.projectId === "7"),
    milestones: mockMilestones.filter((m) => m.projectId === "7"),
  },
  {
    id: "8",
    name: "季度财务报告",
    description: "编制第一季度财务报告",
    status: "待处理",
    priority: "高",
    category: "经营管理",
    createdAt: new Date("2024-03-25"),
    updatedAt: new Date("2024-03-25"),
    dueDate: new Date("2024-04-10"),
    files: [],
    milestones: [],
  },
  {
    id: "9",
    name: "固定资产盘点",
    description: "进行年度固定资产全面盘点",
    status: "进行中",
    priority: "中",
    category: "资产管理",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-20"),
    dueDate: new Date("2024-03-15"),
    files: mockFiles.filter((f) => f.projectId === "9"),
    milestones: [],
  },
  {
    id: "10",
    name: "资产管理系统升级",
    description: "升级资产管理系统到最新版本",
    status: "进行中",
    priority: "中",
    category: "资产管理",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-20"),
    dueDate: new Date("2024-03-20"),
    files: [],
    milestones: mockMilestones.filter((m) => m.projectId === "10"),
  },
  {
    id: "11",
    name: "资产处置审批",
    description: "处理闲置资产处置审批流程",
    status: "已完成",
    priority: "中",
    category: "资产管理",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-10"),
    dueDate: new Date("2024-02-10"),
    files: [],
    milestones: [],
  },
  {
    id: "12",
    name: "董事会议案准备",
    description: "准备年度董事会议案材料",
    status: "已完成",
    priority: "高",
    category: "议案管理",
    createdAt: new Date("2023-12-10"),
    updatedAt: new Date("2024-01-05"),
    dueDate: new Date("2024-01-05"),
    files: mockFiles.filter((f) => f.projectId === "12"),
    milestones: [],
  },
  {
    id: "13",
    name: "股东会议案审核",
    description: "审核股东会提案并准备会议材料",
    status: "进行中",
    priority: "高",
    category: "议案管理",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-03-10"),
    dueDate: new Date("2024-03-25"),
    files: [],
    milestones: mockMilestones.filter((m) => m.projectId === "13"),
  },
  {
    id: "14",
    name: "公司注册变更",
    description: "办理公司注册信息变更手续",
    status: "已完成",
    priority: "中",
    category: "工商管理",
    createdAt: new Date("2023-11-15"),
    updatedAt: new Date("2023-12-20"),
    dueDate: new Date("2023-12-20"),
    files: [],
    milestones: [],
  },
  {
    id: "15",
    name: "营业执照年检",
    description: "完成年度营业执照年检工作",
    status: "待处理",
    priority: "高",
    category: "工商管理",
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-05-01"),
    dueDate: new Date("2024-06-30"),
    files: [],
    milestones: [],
  },
  {
    id: "16",
    name: "办公设备采购",
    description: "采购办公电脑及配套设备",
    status: "进行中",
    priority: "中",
    category: "非工程类采购管理",
    createdAt: new Date("2024-03-28"),
    updatedAt: new Date("2024-04-15"),
    dueDate: new Date("2024-05-10"),
    files: mockFiles.filter((f) => f.projectId === "15"),
    milestones: mockMilestones.filter((m) => m.projectId === "16"),
  },
  {
    id: "17",
    name: "办公家具采购",
    description: "为新办公区域采购办公家具",
    status: "已完成",
    priority: "低",
    category: "非工程类采购管理",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-03-10"),
    dueDate: new Date("2024-03-10"),
    files: [],
    milestones: [],
  },
  {
    id: "18",
    name: "团体保险续保",
    description: "办理员工团体保险续保手续",
    status: "进行中",
    priority: "高",
    category: "保险采购管理",
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-05-20"),
    dueDate: new Date("2024-06-15"),
    files: mockFiles.filter((f) => f.projectId === "18"),
    milestones: [],
  },
  {
    id: "19",
    name: "财产保险投保",
    description: "为公司固定资产投保财产险",
    status: "已完成",
    priority: "中",
    category: "保险采购管理",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-02-05"),
    dueDate: new Date("2024-02-05"),
    files: [],
    milestones: [],
  },
  {
    id: "20",
    name: "合同纠纷处理",
    description: "处理与供应商的合同纠纷案件",
    status: "进行中",
    priority: "高",
    category: "法务管理",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-04-05"),
    dueDate: new Date("2024-05-30"),
    files: mockFiles.filter((f) => f.projectId === "20"),
    milestones: mockMilestones.filter((m) => m.projectId === "20"),
  },
  {
    id: "21",
    name: "劳动合同审核",
    description: "审核新版劳动合同模板",
    status: "已完成",
    priority: "中",
    category: "法务管理",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-15"),
    dueDate: new Date("2024-02-15"),
    files: [],
    milestones: [],
  },
  {
    id: "22",
    name: "知识产权申请",
    description: "申请公司商标和专利保护",
    status: "进行中",
    priority: "中",
    category: "法务管理",
    createdAt: new Date("2024-04-10"),
    updatedAt: new Date("2024-05-01"),
    dueDate: new Date("2024-07-30"),
    files: mockFiles.filter((f) => f.projectId === "22"),
    milestones: [],
  },
  {
    id: "23",
    name: "合规性审查",
    description: "进行公司运营合规性审查",
    status: "已完成",
    priority: "高",
    category: "法务管理",
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date("2024-01-20"),
    dueDate: new Date("2024-01-20"),
    files: [],
    milestones: [],
  },
  {
    id: "24",
    name: "商务谈判支持",
    description: "为重大商务谈判提供法律支持",
    status: "待处理",
    priority: "高",
    category: "法务管理",
    createdAt: new Date("2024-05-20"),
    updatedAt: new Date("2024-05-20"),
    dueDate: new Date("2024-06-20"),
    files: [],
    milestones: [],
  },
  {
    id: "25",
    name: "员工培训计划",
    description: "制定并执行年度员工培训计划",
    status: "进行中",
    priority: "中",
    category: "其他",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-06-01"),
    dueDate: new Date("2024-12-31"),
    files: mockFiles.filter((f) => f.projectId === "25"),
    milestones: [],
  },
  {
    id: "26",
    name: "市场调研分析",
    description: "进行市场竞争环境调研与分析",
    status: "已完成",
    priority: "高",
    category: "经营管理",
    createdAt: new Date("2023-11-05"),
    updatedAt: new Date("2023-12-10"),
    dueDate: new Date("2023-12-10"),
    files: [],
    milestones: [],
  },
  {
    id: "27",
    name: "客户满意度调查",
    description: "开展年度客户满意度调查",
    status: "待处理",
    priority: "中",
    category: "经营管理",
    createdAt: new Date("2024-04-15"),
    updatedAt: new Date("2024-04-15"),
    dueDate: new Date("2024-05-31"),
    files: [],
    milestones: [],
  },
  {
    id: "28",
    name: "内部审计",
    description: "进行年度内部审计工作",
    status: "进行中",
    priority: "高",
    category: "经营管理",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-04-20"),
    dueDate: new Date("2024-06-30"),
    files: [],
    milestones: [],
  },
  {
    id: "29",
    name: "IT基础设施升级",
    description: "升级公司IT基础设施",
    status: "进行中",
    priority: "高",
    category: "资产管理",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-03-30"),
    dueDate: new Date("2024-05-30"),
    files: [],
    milestones: [],
  },
  {
    id: "30",
    name: "UI/UX改进",
    description: "优化用户界面和用户体验",
    status: "待处理",
    priority: "中",
    category: "其他",
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
    dueDate: new Date("2024-03-15"),
    files: [],
    milestones: [],
  },
];

export function getProjectStats(projects: Project[]): ProjectStats {
  return {
    total: projects.length,
    completed: projects.filter((p) => p.status === "已完成").length,
    inProgress: projects.filter((p) => p.status === "进行中").length,
    pending: projects.filter((p) => p.status === "待处理").length,
  };
}

export function getProjectById(id: string): Project | undefined {
  return mockProjects.find((p) => p.id === id);
}

export function getProjectFiles(projectId: string): ProjectFile[] {
  return mockFiles.filter((f) => f.projectId === projectId);
}

export function getProjectMilestones(projectId: string): Milestone[] {
  return mockMilestones.filter((m) => m.projectId === projectId);
}
